[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.21.8"
rustls-pemfile = "1.0.3"
sha2 = "0.10.8"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread", "net", "io-util"] }
tokio-rustls = "0.24.1"
