[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", default-features = false, features = ["std", "derive"] }
env_logger = { version = "0.10.0", default-features = false, features = ["humantime"] }
log = "0.4.20"
rustls = "0.21.8"
rustls-pemfile = "1.0.3"
sha2 = "0.10.8"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread", "net", "io-util"] }
tokio-rustls = "0.24.1"
